<?php

namespace Container3rjw1Hj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeacherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dVVaH_u.App\Entity\Teacher' shared service.
     *
     * @return \App\Entity\Teacher
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dVVaH_u": it needs an instance of "App\\Entity\\Teacher" but this type has been excluded in "config/services.yaml".');
    }
}
