<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerP1c6CIX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP1c6CIX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP1c6CIX.legacy');
=======
if (\class_exists(\ContainerDTRWV7p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDTRWV7p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDTRWV7p.legacy');
<<<<<<< HEAD
>>>>>>> master
=======
>>>>>>> 880060bb5da0c8eda634d33d133a5000981d034f
>>>>>>> 30d3579f095403e4b6f449e111a5699e2e871658

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerP1c6CIX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP1c6CIX\App_KernelDevDebugContainer([
    'container.build_hash' => 'P1c6CIX',
    'container.build_id' => '54e96d34',
    'container.build_time' => 1720366596,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP1c6CIX');
=======
    \class_alias(\ContainerDTRWV7p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDTRWV7p\App_KernelDevDebugContainer([
    'container.build_hash' => 'DTRWV7p',
    'container.build_id' => '29259b3f',
    'container.build_time' => 1720109746,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDTRWV7p');
<<<<<<< HEAD
>>>>>>> master
=======
>>>>>>> 880060bb5da0c8eda634d33d133a5000981d034f
>>>>>>> 30d3579f095403e4b6f449e111a5699e2e871658
