<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerOsaKUrs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOsaKUrs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOsaKUrs.legacy');
=======
if (\class_exists(\ContainerZEEF3bZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZEEF3bZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZEEF3bZ.legacy');
>>>>>>> origin/sandesh

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerOsaKUrs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOsaKUrs\App_KernelDevDebugContainer([
    'container.build_hash' => 'OsaKUrs',
    'container.build_id' => '8e4fcb7e',
    'container.build_time' => 1720410133,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOsaKUrs');
=======
    \class_alias(\ContainerZEEF3bZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZEEF3bZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZEEF3bZ',
    'container.build_id' => 'd0891ea1',
    'container.build_time' => 1720370787,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZEEF3bZ');
>>>>>>> origin/sandesh
