<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerBkA9ba0/getAttendanceControlleraddAttendanceService.php
namespace ContainerBkA9ba0;
========
namespace ContainerDQ5ka7F;

>>>>>>>> origin/sandesh:backend/var/cache/dev/ContainerDQ5ka7F/getAttendanceControlleraddAttendanceService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttendanceControlleraddAttendanceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P.blNFL.App\Controller\AttendanceController::addAttendance()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.P.blNFL'] ?? $container->load('get_ServiceLocator_P_BlNFLService'));

        if (isset($container->privates['.service_locator.P.blNFL.App\\Controller\\AttendanceController::addAttendance()'])) {
            return $container->privates['.service_locator.P.blNFL.App\\Controller\\AttendanceController::addAttendance()'];
        }

        return $container->privates['.service_locator.P.blNFL.App\\Controller\\AttendanceController::addAttendance()'] = $a->withContext('App\\Controller\\AttendanceController::addAttendance()', $container);
    }
}
