<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerP1c6CIX/get_AssetMapper_Importmap_Command_Audit_LazyService.php
namespace ContainerP1c6CIX;
========
namespace ContainerDTRWV7p;

>>>>>>>> 880060bb5da0c8eda634d33d133a5000981d034f:backend/var/cache/dev/ContainerDTRWV7p/get_AssetMapper_Importmap_Command_Audit_LazyService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_AssetMapper_Importmap_Command_Audit_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.asset_mapper.importmap.command.audit.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.asset_mapper.importmap.command.audit.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('importmap:audit', [], 'Check for security vulnerability advisories for dependencies', false, #[\Closure(name: 'asset_mapper.importmap.command.audit', class: 'Symfony\\Component\\AssetMapper\\Command\\ImportMapAuditCommand')] fn (): \Symfony\Component\AssetMapper\Command\ImportMapAuditCommand => ($container->privates['asset_mapper.importmap.command.audit'] ?? $container->load('getAssetMapper_Importmap_Command_AuditService')));
    }
}
