<?php

<<<<<<<< HEAD:backend/var/cache/dev/ContainerP1c6CIX/getKeyAnalyzerCommandService.php
namespace ContainerP1c6CIX;
========
namespace ContainerDTRWV7p;

<<<<<<< HEAD
>>>>>>>> master:backend/var/cache/dev/ContainerDTRWV7p/getKeyAnalyzerCommandService.php
=======
>>>>>>>> 880060bb5da0c8eda634d33d133a5000981d034f:backend/var/cache/dev/ContainerDTRWV7p/getKeyAnalyzerCommandService.php
>>>>>>> 30d3579f095403e4b6f449e111a5699e2e871658

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeyAnalyzerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Jose\Component\Console\KeyAnalyzerCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\KeyAnalyzerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-framework'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Library'.\DIRECTORY_SEPARATOR.'Console'.\DIRECTORY_SEPARATOR.'KeyAnalyzerCommand.php';

        $container->privates['Jose\\Component\\Console\\KeyAnalyzerCommand'] = $instance = new \Jose\Component\Console\KeyAnalyzerCommand(($container->services['Jose\\Component\\KeyManagement\\Analyzer\\KeyAnalyzerManager'] ?? self::getKeyAnalyzerManagerService($container)));

        $instance->setName('key:analyze');
        $instance->setDescription('JWK quality analyzer.');

        return $instance;
    }
}
