<?php

<<<<<<< HEAD
namespace ContainerBkA9ba0;
=======
<<<<<<< HEAD
<<<<<<< HEAD:backend/var/cache/dev/ContainerDTRWV7p/getKeysetAnalyzerCommandService.php
<<<<<<<< HEAD:backend/var/cache/dev/ContainerP1c6CIX/getKeysetAnalyzerCommandService.php
namespace ContainerP1c6CIX;
========
namespace ContainerDTRWV7p;

<<<<<<< HEAD
>>>>>>>> master:backend/var/cache/dev/ContainerDTRWV7p/getKeysetAnalyzerCommandService.php
=======
>>>>>>>> 880060bb5da0c8eda634d33d133a5000981d034f:backend/var/cache/dev/ContainerDTRWV7p/getKeysetAnalyzerCommandService.php
>>>>>>> 30d3579f095403e4b6f449e111a5699e2e871658
=======
namespace ContainerBkA9ba0;
>>>>>>> 43717bd8fbd4660ee8dfa0df411eea0544a1c6da:backend/var/cache/dev/ContainerBkA9ba0/getKeysetAnalyzerCommandService.php
=======
namespace ContainerBkA9ba0;
>>>>>>> 43717bd8fbd4660ee8dfa0df411eea0544a1c6da
>>>>>>> 081930ac77502788e8c5bf70fc329cbfccb254a4

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeysetAnalyzerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Jose\Component\Console\KeysetAnalyzerCommand' shared autowired service.
     *
     * @return \Jose\Component\Console\KeysetAnalyzerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'web-token'.\DIRECTORY_SEPARATOR.'jwt-framework'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Library'.\DIRECTORY_SEPARATOR.'Console'.\DIRECTORY_SEPARATOR.'KeysetAnalyzerCommand.php';

        $container->privates['Jose\\Component\\Console\\KeysetAnalyzerCommand'] = $instance = new \Jose\Component\Console\KeysetAnalyzerCommand(($container->services['Jose\\Component\\KeyManagement\\Analyzer\\KeysetAnalyzerManager'] ?? self::getKeysetAnalyzerManagerService($container)), ($container->services['Jose\\Component\\KeyManagement\\Analyzer\\KeyAnalyzerManager'] ?? self::getKeyAnalyzerManagerService($container)));

        $instance->setName('keyset:analyze');
        $instance->setDescription('JWKSet quality analyzer.');

        return $instance;
    }
}
